[package]
name = "rustffi"
version = "0.1.0"
authors = ["Daniel García Moreno <danigm@wadobo.com>"]

[lib]
#crate-type = ['cdylib']
crate-type = ['staticlib']

[dependencies]
libc = '0.2.0'

[build-dependencies]
gcc = "0.3"
